export const SocialStrategies = {
  apple: "Apple",
  amazon: "Amazon",
  aol: "Aol",
  baidu: "百度",
  bitbucket: "Bitbucket",
  box: "Box",
  dropbox: "Dropbox",
  dwolla: "Dwolla",
  ebay: "ebay",
  exact: "Exact",
  facebook: "Facebook",
  fitbit: "Fitbit",
  github: "GitHub",
  "google-openid": "Google OpenId",
  "google-oauth2": "Google",
  instagram: "Instagram",
  linkedin: "LinkedIn",
  miicard: "miiCard",
  paypal: "PayPal",
  "paypal-sandbox": "PayPal Sandbox",
  planningcenter: "Planning Center",
  renren: "人人",
  salesforce: "Salesforce",
  "salesforce-community": "Salesforce Community",
  "salesforce-sandbox": "Salesforce (sandbox)",
  evernote: "Evernote",
  "evernote-sandbox": "Evernote (sandbox)",
  shopify: "Shopify",
  soundcloud: "Soundcloud",
  thecity: "The City",
  "thecity-sandbox": "The City (sandbox)",
  thirtysevensignals: "37 Signals",
  twitter: "Twitter",
  vkontakte: "vKontakte",
  windowslive: "Microsoft Account",
  wordpress: "Wordpress",
  yahoo: "Yahoo!",
  yammer: "Yammer",
  yandex: "Yandex",
  weibo: "新浪微博"
};
